steps:
  # Step 1: Install dependencies
  - name: python:3.10
    id: Install dependencies
    entrypoint: bash
    args:
      - -c
      - |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

  # Step 2: Run linting with flake8
  - name: python:3.10
    id: Lint code
    entrypoint: bash
    args:
      - -c
      - |
        python -m pip install flake8
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  # Step 3: Run tests with pytest
  - name: python:3.10
    id: Run tests
    entrypoint: bash
    args:
      - -c
      - |
        python -m pip install pytest
        pytest

  # Step 4: Deploy to Google App Engine
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
    id: Deploy to App Engine
    entrypoint: bash
    args:
      - -c
      - |
        gcloud app deploy --quiet --allow-unauthenticated

timeout: "600s"
