name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest gunicorn
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
        
    - name: Decode GCP Service Account Key
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > gcp-service-account-key.json
        
    - name: Deploy to Google Cloud
      uses: google-github-actions/deploy-appengine@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        key_file: gcp-service-account-key.json
        entrypoint: 'gunicorn -b 0.0.0.0:8080 app:app'
